def validar_usuario(user_id: str, password: str) -> bool:
    ...

def is_becario(user_id: str) -> bool:
    ...

def add_responsable(new_responsable_email: str, new_password: str) -> bool:
    ...
    
def add_becario(new_becario_email: str, new_password: str, responsable_email: str) -> bool:
    ...

